//
//  MoveInputSuppression.swift
//  Project: Thaw
//
//  Copyright (Ice) © 2023–2025 Jordan Baird
//  Copyright (Thaw) © 2026 Toni Förster
//  Licensed under the GNU GPLv3

import Cocoa

/// Ported from `feat/macos-27-experimental`'s `MenuBarItemEventSupport.swift`.
///
/// Suppresses real user mouse input for the duration of a synthetic
/// cursor-move gesture by inserting an ephemeral head-insert event tap at
/// the HID level. Events created from ``makeSyntheticMoveEventSource()``
/// carry a nonzero `eventSourceUserData` (inherited from the dedicated
/// `CGEventSource` at creation time) and pass through untouched; only
/// events with a zero `eventSourceUserData` — i.e. events actually
/// generated by hardware, or by any other `CGEventSource` in the app that
/// never sets `userData` — are swallowed.
///
/// NOTE (found while testing on a macOS 27 host): `CGEvent
/// .setIntegerValueField(.eventSourceUserData, value:)` is a no-op when
/// called on an already-created event on that SDK — the field only
/// reflects whatever the event's `CGEventSource.userData` was AT CREATION
/// TIME. Because this branch ships to macOS 26 machines and that behavior
/// is unverified there, marking is done at the *source* level
/// (``makeSyntheticMoveEventSource()``), which is documented, version
/// -stable CoreGraphics behavior on every macOS release. Per-event marking
/// via ``markSyntheticMoveEvent(_:)`` is kept only as a defense-in-depth
/// shim for any OS where the per-event write does take effect.
nonisolated enum MoveInputSuppression {
    /// Sentinel value stamped into `eventSourceUserData` on every synthetic
    /// event posted by a cursor-move gesture, spelling "ThawMove" in ASCII.
    static let syntheticMoveUserData: Int64 = 0x5468_6177_4D6F_7665

    /// Mouse event types suppressed while a synthetic move gesture is in
    /// flight.
    static let suppressedMouseEventTypes: [CGEventType] = [
        .leftMouseDown, .leftMouseUp, .rightMouseDown, .rightMouseUp,
        .mouseMoved, .leftMouseDragged, .rightMouseDragged, .scrollWheel,
        .otherMouseDown, .otherMouseUp, .otherMouseDragged,
    ]

    /// Creates a dedicated `CGEventSource` for a single synthetic-move
    /// gesture, with `userData` set to ``syntheticMoveUserData`` before any
    /// event is created from it. Events created from this source inherit
    /// the nonzero `userData` at creation time — this is the
    /// version-stable path across macOS releases (unlike per-event
    /// `setIntegerValueField(.eventSourceUserData, ...)` writes, see the
    /// type-level note above). Uses `.hidSystemState`, matching
    /// `MenuBarItemManager.getEventSource`'s default state ID.
    static func makeSyntheticMoveEventSource() throws -> CGEventSource {
        guard let source = CGEventSource(stateID: .hidSystemState) else {
            throw MenuBarItemManager.EventError.invalidEventSource
        }
        source.userData = syntheticMoveUserData
        return source
    }

    /// Marks the given event as a synthetic move event so it is never
    /// suppressed by ``withUserMouseInputSuppressed(_:)``. This is a
    /// belt-and-suspenders compatibility shim: on hosts where per-event
    /// `eventSourceUserData` writes take effect, this is redundant but
    /// harmless alongside an event already created from
    /// ``makeSyntheticMoveEventSource()``; on hosts where the write is a
    /// no-op (confirmed on macOS 27), the event's marking still comes from
    /// its source, so nothing is lost.
    static func markSyntheticMoveEvent(_ event: CGEvent) {
        event.setIntegerValueField(.eventSourceUserData, value: syntheticMoveUserData)
    }

    /// Returns whether the given event should be suppressed, i.e. removed
    /// from the event stream. Only events of a suppressed mouse type whose
    /// `eventSourceUserData` is zero (unsigned, meaning hardware-generated)
    /// are suppressed. Any event this app has already stamped with nonzero
    /// user data — whether via ``markSyntheticMoveEvent(_:)`` or via the
    /// `ObjectIdentifier`-derived value that
    /// `CGEvent.menuBarItemEvent(item:source:type:location:)` sets — passes
    /// through.
    static func shouldSuppress(_ event: CGEvent) -> Bool {
        guard suppressedMouseEventTypes.contains(event.type) else { return false }
        return event.getIntegerValueField(.eventSourceUserData) == 0
    }

    /// Runs `operation` with real user mouse input suppressed for its
    /// duration via an ephemeral head-insert HID event tap. If the tap
    /// cannot be created, `operation` proceeds unsuppressed.
    @MainActor
    static func withUserMouseInputSuppressed<T>(
        _ operation: () async throws -> T
    ) async throws -> T {
        let tap = EventTap(
            label: "Move input suppression",
            types: suppressedMouseEventTypes,
            location: .hidEventTap,
            placement: .headInsertEventTap,
            option: .defaultTap
        ) { _, event in
            shouldSuppress(event) ? nil : event
        }

        if tap.isValid {
            tap.enable()
        } else {
            diagLog.warning("Move input suppression tap could not be created")
        }
        defer { tap.invalidate() }
        return try await operation()
    }

    /// Logger for this file. `MenuBarItemManager.diagLog` is `fileprivate`
    /// to `MenuBarItemManager.swift`, so this file uses its own category.
    private static let diagLog = DiagLog(category: "MoveInputSuppression")
}
