name: Build DMG

on:
  workflow_dispatch:

concurrency:
  group: build-dmg-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-dmg:
    runs-on: macos-26
    env:
      APP_NAME: "Thaw.app"
      DMG_NAME: "Thaw-dev.dmg"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      # Issues with other Xcode versions, so we need to specify the version explicitly
      - run: sudo xcode-select -s /Applications/Xcode_26.6.app/Contents/Developer

      - name: Configure signing
        uses: thaw-app/org-ci/actions/configure-signing@0e335f8ccf7571be6a8cb0df2b947b1728086def
        with:
          apple-application-cert: ${{ secrets.APPLE_APPLICATION_CERT }}
          apple-application-cert-password: ${{ secrets.APPLE_APPLICATION_CERT_PASSWORD }}
          apple-id: ${{ secrets.APPLE_ID }}
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}

      - name: Build
        uses: thaw-app/org-ci/actions/build@0e335f8ccf7571be6a8cb0df2b947b1728086def
        with:
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          project-name: Thaw.xcodeproj
          scheme-name: Thaw
          deployment-target: "26.0"

      - name: Export Archive
        uses: thaw-app/org-ci/actions/export-and-package@0e335f8ccf7571be6a8cb0df2b947b1728086def
        with:
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          app-name: ${{ env.APP_NAME }}
          dmg-name: ${{ env.DMG_NAME }}

      - name: Notarize
        uses: thaw-app/org-ci/actions/notarize-and-validate@0e335f8ccf7571be6a8cb0df2b947b1728086def
        with:
          dmg-name: ${{ env.DMG_NAME }}
          app-name: ${{ env.APP_NAME }}

      - name: Upload DMG
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Thaw-dmg
          path: build/${{ env.DMG_NAME }}
          retention-days: 3

      - name: Cleanup keychain
        if: always()
        run: security delete-keychain "$RUNNER_TEMP/buildagent.keychain" || true
