name: Close stale issues

on:
  schedule:
    - cron: "0 0 */3 * *" # Once every 3 days
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    if: github.repository == 'thaw-app/Thaw'
    runs-on: ubuntu-slim
    permissions:
      issues: write
    steps:
      - uses: thaw-app/org-ci/actions/close-stale-issues@61f345397193bf3f9356c4f6179fb6ed4c84dd45
